# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/python-mdd',
                'doc_host': 'https://rkimura47.github.io',
                'git_url': 'https://github.com/rkimura47/python-mdd',
                'lib_path': 'python_mdd'},
  'syms': {'python_mdd.core': {'python_mdd.core.foo': ('core.html#foo', 'python_mdd/core.py')}}}