project:
  type: website
  preview:
    host: 0.0.0.0
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
    contents:
      auto: "*.ipynb"

metadata-files: [nbdev.yml]
